=== anass989/up/xml/clientes.dtd
<!ELEMENT clientes (cliente*)>
<!ELEMENT cliente (nombre*, descripcion*)>
  <!ATTLIST cliente slide CDATA>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== anass989/up/xml/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<?xml-stylesheet type="text/xsl" href="clientes.xsl"?>
<clientes>
  <cliente slide="1">
    <nombre>Abdo Boukhari</nombre>
    <descripcion>Idea de negocio: Obrador de Pastelería</descripcion>
  </cliente>
  <cliente slide="2">
    <nombre>Álvaro Cafetería Zayas</nombre>
    <descripcion>Propuesta de servicio</descripcion>
  </cliente>
  <cliente slide="3">
    <nombre>Bar Darwin</nombre>
    <descripcion>Curso Formativo de Eficiencia en Costes Materias Primas</descripcion>
  </cliente>
</clientes>
